name: 'lenovo-sign'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '5 16,22 * * *'

jobs:
  tieba_sign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'
      - name: 'Install dependencies'
        run: pip3 install -r requirements.txt
      - name: 'Start Sign'
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python3 lenovo_sign.py
